// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aowssoilwdakirkzplnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvd3Nzb2lsd2Rha2lya3pwbG5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODc0ODQsImV4cCI6MjA1OTQ2MzQ4NH0.5pCC41gB-7HbI7t26ovA7VCmzMzEolXzW1YRxXhj_qQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);